[[mgr.prepend_keymap]]
on   = [ "<C-s>" ]
run  = 'shell "$SHELL" --block --confirm'
desc = "Open shell here"

[[mgr.prepend_keymap]]
on  = [ "T" ]
run = "plugin --sync max-preview"

[[mgr.prepend_keymap]]
on   = [ "l" ]
run  = "plugin --sync smart-enter"
desc = "Enter the child directory, or open the file"

[[mgr.prepend_keymap]]
on   = [ "z" ]
run  = "plugin zoxide"
desc = "Jump to directory using zoxide"
